name: Lint Codebase

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Prek
        uses: j178/prek-action@v2
